pipeline {
    agent any

    stages {
        stage('Pack Velen Top') {
            when {
                changeset "src/hak/velen_top/*"
            }
            steps {
                echo 'Packing Velen top'
                 script {
                    sh "docker run --rm -t -v \$(pwd):/nasher -v \$(pwd):/nasher urothis/nwnee-community-images:nasher-8193.34 pack velen_top --clean --verbose --yes"
                }
            }
        }
        stage('Pack Velen Tiles8') {
            when {
                changeset "src/hak/velen_tiles8/*"
            }
            steps {
                echo 'Packing Velen top'
                 script {
                    sh "docker run --rm -t -v \$(pwd):/nasher urothis/nwnee-community-images:nasher-8193.34 pack velen_tiles8 --clean --verbose --yes"
                }
            }
        }
        stage('Pack Velen Tiles7') {
            when {
                changeset "src/hak/velen_tiles7/*"
            }
            steps {
                echo 'Packing Velen top'
                 script {
                    sh "docker run --rm -t -v \$(pwd):/nasher urothis/nwnee-community-images:nasher-8193.34 pack velen_top --clean --verbose --yes"
                }
            }
        }
        stage('Pack Velen Tiles6') {
            when {
                changeset "src/hak/velen_tiles6/*"
            }
            steps {
                echo 'Packing Velen top'
                 script {
                    sh "docker run --rm -t -v \$(pwd):/nasher urothis/nwnee-community-images:nasher-8193.34 pack velen_top --clean --verbose --yes"
                }
            }
        }
        stage('Pack Velen Tiles5') {
            when {
                changeset "src/hak/velen_tiles5/*"
            }
            steps {
                echo 'Packing Velen top'
                 script {
                    sh "docker run --rm -t -v \$(pwd):/nasher urothis/nwnee-community-images:nasher-8193.34 pack velen_top --clean --verbose --yes"
                }
            }
        }
        stage('Pack Velen Tiles4') {
            when {
                changeset "src/hak/velen_tiles4/*"
            }
            steps {
                echo 'Packing Velen top'
                 script {
                    sh "docker run --rm -t -v \$(pwd):/nasher urothis/nwnee-community-images:nasher-8193.34 pack velen_top --clean --verbose --yes"
                }
            }
        }
        stage('Pack Velen Tiles3') {
            when {
                changeset "src/hak/velen_tiles3/*"
            }
            steps {
                echo 'Packing Velen top'
                 script {
                    sh "docker run --rm -t -v \$(pwd):/nasher urothis/nwnee-community-images:nasher-8193.34 pack velen_top --clean --verbose --yes"
                }
            }
        }
        stage('Pack Velen Tiles2') {
            when {
                changeset "src/hak/velen_tiles2/*"
            }
            steps {
                echo 'Packing Velen top'
                 script {
                    sh "docker run --rm -t -v \$(pwd):/nasher urothis/nwnee-community-images:nasher-8193.34 pack velen_top --clean --verbose --yes"
                }
            }
        }
        stage('Pack Velen Tiles1') {
            when {
                changeset "src/hak/velen_tiles1/*"
            }
            steps {
                echo 'Packing Velen top'
                 script {
                    sh "docker run --rm -t -v \$(pwd):/nasher urothis/nwnee-community-images:nasher-8193.34 pack velen_top --clean --verbose --yes"
                }
            }
        }
        stage('Pack Velen Anim') {
            when {
                changeset "src/hak/velen_tiles1/*"
            }
            steps {
                echo 'Packing Velen top'
                 script {
                    sh "docker run --rm -t -v \$(pwd):/nasher urothis/nwnee-community-images:nasher-8193.34 pack velen_top --clean --verbose --yes"
                }
            }
        }
    }
    post {
        always {
            discordSend description: "Build completed.", footer: "Build results for the Amia module", link: env.BUILD_URL, result: currentBuild.currentResult, title: "Module Deployment Results (click to see more)", webhookURL: "https://discord.com/api/webhooks/996982337130733599/frNKPqME61E1c5wHTqDvWC8JTttNDZ5y6lanuL4oooc-Bc4StI8ln7cyDVr1DywSXeVS"
        }
        success {
            echo 'Build success'
            archiveArtifacts artifacts: '*.hak', followSymlinks: false
            archiveArtifacts artifacts: '*.tlk', followSymlinks: false
            sh "sudo rm -rf Amia.mod"
        }
    }
}