pipeline {
    agent any

    environment {
        CHANGES = 'false'
    }
    
    stages {
        stage('Check for changes'){
            when{
                not{
                    changeset "content/src/hak/**/**/**"
                }
                expression{
                    return params.BUILD_ALL == 'No'
                }
            }
            steps{
                echo "Nothing to do. Exiting."
                exit 1
            }
        }
        stage('Before all'){
            steps{
                discordSend description: "Build for Velen content kicked off", footer: "Build start", link: env.BUILD_URL, title: "Build Kickoff", webhookURL: params.WEBHOOK
            }
        }
        stage('Pack Velen Top') {
            when {
                changeset "content/src/hak/velen_2das/**/**"
            }
            steps {
                discordSend description: "Packing Velen 2das", footer: "Velen 2das", link: env.BUILD_URL, title: "Packaging Hak", webhookURL: params.WEBHOOK
                echo 'Packing Velen 2das'
                 script {
                    sh "chmod +x content/pack.sh"
                    sh "dos2unix content/pack.sh"
                    sh "./content/pack.sh hak velen_2das"
                }
            }
        }
        stage('Pack Velen Armors') {
            when {
                changeset "content/src/hak/velen_armors/**/**"
            }
            steps {
                discordSend description: "Packing Velen Armors", footer: "Velen Armors", link: env.BUILD_URL, title: "Packaging Hak", webhookURL: params.WEBHOOK
                 script {
                    sh "chmod +x content/pack.sh"
                    sh "dos2unix content/pack.sh"
                    sh "./content/pack.sh hak velen_armors"
                }
            }
        }
        stage('Pack Velen Core0') {
            when {
                changeset "content/src/hak/velen_core0/**/**"
            }
            steps {
                discordSend description: "Packing Velen Core0", footer: "Velen Core0", link: env.BUILD_URL, title: "Packaging Hak", webhookURL: params.WEBHOOK
                 script {
                    sh "chmod +x content/pack.sh"
                    sh "dos2unix content/pack.sh"
                    sh "./content/pack.sh hak velen_core0"
                }
            }
        }
        stage('Pack Velen Core1') {
            when {
                changeset "content/src/hak/velen_core1/**/**"
            }
            steps {
                discordSend description: "Packing Velen Core1", footer: "Velen Core1", link: env.BUILD_URL, title: "Packaging Hak", webhookURL: params.WEBHOOK
                 script {
                    sh "chmod +x content/pack.sh"
                    sh "dos2unix content/pack.sh"
                    sh "./content/pack.sh hak velen_core1"
                }
            }
        }
        stage('Pack Velen Core2') {
            when {
                changeset "content/src/hak/velen_core2/**/**"
            }
            steps {
                discordSend description: "Packing Velen Core2", footer: "Velen Core2", link: env.BUILD_URL, title: "Packaging Hak", webhookURL: params.WEBHOOK
                 script {
                    sh "chmod +x content/pack.sh"
                    sh "dos2unix content/pack.sh"
                    sh "./content/pack.sh hak velen_core2"
                }
            }
        }
        stage('Pack Velen Doors') {
            when {
                changeset "content/src/hak/velen_doors/**/**"
            }
            steps {
                discordSend description: "Packing Velen Doors", footer: "Velen Doors", link: env.BUILD_URL, title: "Packaging Hak", webhookURL: params.WEBHOOK
                 script {
                    sh "chmod +x content/pack.sh"
                    sh "dos2unix content/pack.sh"
                    sh "./content/pack.sh hak velen_doors"
                }
            }
        }
        stage('Pack Velen Facelift') {
            when {
                changeset "content/src/hak/velen_facelift/**/**"
            }
            steps {
                discordSend description: "Packing Velen Facelift", footer: "Velen tiles3", link: env.BUILD_URL, title: "Packaging Hak", webhookURL: params.WEBHOOK
                 script {
                    sh "chmod +x content/pack.sh"
                    sh "dos2unix content/pack.sh"
                    sh "./content/pack.sh hak velen_facelift"
                }
            }
        }
        stage('Pack Velen Pheno') {
            when {
                changeset "content/src/hak/velen_phenos/**/**"
            }
            steps {
                discordSend description: "Packing Velen Pheno", footer: "Velen tiles2", link: env.BUILD_URL, title: "Packaging Hak", webhookURL: params.WEBHOOK
                 script {
                    sh "chmod +x content/pack.sh"
                    sh "dos2unix content/pack.sh"
                    sh "./content/pack.sh hak velen_phenos"
                }
            }
        }
        stage('Pack Velen Portraits') {
            when {
                changeset "content/src/hak/velen_portraits/**/**"
            }
            steps {
                discordSend description: "Packing Velen Portraits", footer: "Velen tiles1", link: env.BUILD_URL, title: "Packaging Hak", webhookURL: params.WEBHOOK
                 script {
                    sh "chmod +x content/pack.sh"
                    sh "dos2unix content/pack.sh"
                    sh "./content/pack.sh hak velen_portraits"
                }
            }
        }
        stage('Pack Velen Reskins') {
            when {
                changeset "content/src/hak/velen_reskins/**/**"
            }
            steps {
                discordSend description: "Packing Velen Reskins", footer: "Velen Reskins", link: env.BUILD_URL, title: "Packaging Hak", webhookURL: params.WEBHOOK
                 script {
                    sh "chmod +x content/pack.sh"
                    sh "dos2unix content/pack.sh"
                    sh "./content/pack.sh hak velen_reskins"
                }
            }
        }
        stage('Pack Velen Skies') {
            when {
                changeset "content/src/hak/velen_skies/**/**"
            }
            steps {
                discordSend description: "Packing Velen Skies", footer: "Velen Skies", link: env.BUILD_URL, title: "Packaging Hak", webhookURL: params.WEBHOOK
                 script {
                    sh "chmod +x content/pack.sh"
                    sh "dos2unix content/pack.sh"
                    sh "./content/pack.sh hak velen_skies"
                }
            }
        }
        stage('Pack Velen Tiles') {
            when {
                changeset "content/src/hak/velen_tiles/**/**"
            }
            steps {
                discordSend description: "Packing Velen cont", footer: "Velen Tiles", link: env.BUILD_URL, title: "Packaging Hak", webhookURL: params.WEBHOOK
                 script {
                    sh "chmod +x content/pack.sh"
                    sh "dos2unix content/pack.sh"
                    sh "./content/pack.sh hak velen_tiles"
                }
            }
        }
        stage('Pack Velen VFX') {
            when {
                changeset "content/src/hak/velen_vfx/**/**"
            }
            steps {
                discordSend description: "Packing Velen vfx", footer: "Velen vfx", link: env.BUILD_URL, title: "Packaging Hak", webhookURL: params.WEBHOOK
                 script {
                    sh "chmod +x content/pack.sh"
                    sh "dos2unix content/pack.sh"
                    sh "./content/pack.sh hak velen_vfx"
                }
            }
        }
        stage('Pack Velen tlk') {
            when {
                changeset "content/src/tlk/velen/tlk/**"
            }
            steps {
                discordSend description: "Packing Velen tlk", footer: "Velen TLK", link: env.BUILD_URL, title: "Packaging TLK", webhookURL: params.WEBHOOK
                 script {
                    sh "chmod +x content/pack.sh"
                    sh "dos2unix content/pack.sh"
                    sh "./content/pack.sh tlk tlk"
                }
            }
        }
        stage('Pack everything') {
            when {
                expression {
                    return params.BUILD_ALL == 'Yes'
                }
            }
            steps {
                discordSend description: "Packing everything", footer: "Packing everything", link: env.BUILD_URL, title: "Packaging All Tilesent", webhookURL: params.WEBHOOK
                 script {
                    sh "chmod +x content/bundle-all.sh"
                    sh "dos2unix content/bundle-all.sh"
                    sh "./content/bundle-all.sh"
                }
            }
        }
    }
    post {
        always {
            echo 'Finalizing results.' 
        }
        success {
            discordSend description: "", footer: "Successful build results for Velen content", link: env.BUILD_URL, result: currentBuild.currentResult, title: "Build Complete", webhookURL: params.WEBHOOK
            archiveArtifacts artifacts: 'content/*.hak', followSymlinks: false, allowEmptyArchive: true
            archiveArtifacts artifacts: 'content/*.tlk', followSymlinks: false, allowEmptyArchive: true
            archiveArtifacts artifacts: 'content/*.zip', followSymlinks: false, allowEmptyArchive: true
            echo 'Build complete'
        }
    }
}